dat<-read.table(file="f.txt", sep=",")
dat
d<-as.numeric(dat)
d
sr_znach<-mean(d)
sr_znach
disp<-var(d)
disp
sd(d)
otkl<-sqrt(disp)
otkl
which.max(table(d))
mediana<-median(d)
mediana
a<-table(d)
a
zn<-sort(unique(d))
zn
n<-length(d)
n
koeff_asimm<-sum((zn-sr_znach)^3*a)/(n*otkl^3)
koeff_asimm
koeff_exces<-sum((zn-sr_znach)^4*a)/(n*otkl^4) - 3
koeff_exces
koeff_var<-(otkl*100)/sr_znach
koeff_var
otn_lin_otkl<-(sum(abs(zn-sr_znach)*a)*100)/(n*sr_znach)
otn_lin_otkl
m<-3
first<-1:m
first
d1<-d[-first]
d1
n1<-length(d1)
last<-(n1-m+1):n1
d2<-d1[-last]
d2
usch_srdn<-sum(d2)/(n-2*m)
usch_srdn

